# Generated by Django 4.2.11 on 2026-04-08 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to='original/%Y/%m/%d/', validators=[dms.models.validate_document_extension])),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX')], max_length=8)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_ASSIGNED', 'Not Assigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PENDING_APPROVAL', 'Pending Approval')], default='NOT_ASSIGNED', max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_merged_file', models.FileField(blank=True, null=True, upload_to='final/%Y/%m/%d/')),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_page_capacity', models.PositiveIntegerField(default=10)),
                ('is_active_session', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('split_file', models.FileField(blank=True, null=True, upload_to='split/%Y/%m/%d/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('NOT_ASSIGNED', 'Not Assigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PENDING_APPROVAL', 'Pending Approval')], default='NOT_ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('download_started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pages', to='dms.resourceprofile')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dms.document')),
            ],
            options={
                'ordering': ('document_id', 'page_number'),
                'unique_together': {('document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('UPLOAD_DOC', 'Upload document'), ('SPLIT_DOC', 'Split document'), ('ASSIGN_PAGE', 'Assign page'), ('DOWNLOAD_PAGE', 'Download page'), ('SUBMIT_PAGE', 'Submit page'), ('MERGE_DOC', 'Merge document'), ('APPROVE_PAGE', 'Approve page')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dms.document')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dms.documentpage')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssignmentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('NO_CAPACITY', 'No capacity'), ('NO_ACTIVE_RESOURCE', 'No active resource')], max_length=20)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='dms.documentpage')),
            ],
            options={
                'ordering': ('queued_at',),
            },
        ),
    ]
