# Generated by Django 4.2.11 on 2026-04-11 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_merged_revision(apps, schema_editor):
    Document = apps.get_model("dms", "Document")
    Document.objects.exclude(final_merged_file="").filter(final_merged_file__isnull=False).update(merged_revision=1)


def noop_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='merged_revision',
            field=models.PositiveIntegerField(default=0, help_text='Current merged file version number (v1, v2, …). Increments on each merge or correction upload.'),
        ),
        migrations.CreateModel(
            name='MergedFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='merged_versions/%Y/%m/%d/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_versions_saved', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_version_history', to='dms.document')),
            ],
            options={
                'ordering': ('version',),
                'unique_together': {('document', 'version')},
            },
        ),
        migrations.RunPython(backfill_merged_revision, noop_backfill),
    ]
