# Generated by Django 4.2.11 on 2026-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_merged_file_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('NOT_ASSIGNED', 'Not Assigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PENDING_APPROVAL', 'Pending Approval'), ('ON_HOLD', 'On Hold')], default='NOT_ASSIGNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='status',
            field=models.CharField(choices=[('NOT_ASSIGNED', 'Not Assigned'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PENDING_APPROVAL', 'Pending Approval'), ('ON_HOLD', 'On Hold'), ('REASSIGNED', 'Reassigned')], default='NOT_ASSIGNED', max_length=20),
        ),
    ]
