# Generated by Django 4.2.11 on 2026-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_hold_and_split_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='prioritized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceprofile',
            name='manual_upload_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, admin can manually assign held/reassigned jobs to this resource; auto-assignment skips this resource.'),
        ),
    ]
